# Generated by Django 5.0.4 on 2024-04-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.IntegerField(null=True)),
                ('idade', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
