# Generated by Django 5.0.4 on 2024-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroclient', '0003_alter_cliente_cpf_alter_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
