# Generated by Django 5.0.4 on 2024-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=60)),
                ('medico', models.CharField(max_length=60)),
                ('horario', models.CharField(max_length=60)),
                ('marcaData', models.DateTimeField(auto_now_add=True)),
                ('consulData', models.DateTimeField()),
            ],
        ),
    ]
