# Generated by Django 5.0.4 on 2024-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='consulData',
            field=models.DateField(),
        ),
    ]
